baseurl = "http://kapelal.io/"
theme = "cocoa-eh"
builddrafts = true
canonifyurls = true
contentdir = "content"
languageCode = "en-US"
layoutdir = "layouts"
publishdir = "public"
author = "Roberto Barros De Sousa"
title = "Kapelal Blog !"
disqusshortname = ""
pluralizelisttitles = false

[permalinks]
blog = "blog/:slug/"

[params]
dateform = "Jan 2, 2006"
dateformfull = "Mon Jan 2 2006 15:04:05 MST"
description = "Example blog"
copyright = "Copyright Â© 2018 Roberto Barros De Sousa"
logofile = "img/logo.png"
faviconfile = "img/logo.png"
highlightjs = true
progressively = true
align_left = false
lang = "en"
github = "Kapelal"
email = "dess roberto at gmail com"
linkedin = "roberto-barros-de-sousa-16635665"
twitter = "dsousa_rob"
social_banner = "img/banner.png"
posts_navigation = true
small_banner_logo = false
